sonata_user:
    impersonating:
        route: sonata_admin_dashboard
    manager_type: mongodb # can be orm or mongodb
    class:                  # Entity Classes
        user:               App\Document\User
        group:              App\Application\Sonata\UserBundle\Document\Group

    admin:                  # Admin Classes
        user:
            class:          App\Admin\UserAdmin
            controller:     App\Controller\Admin\UserAdminController
            translation:    SonataUserBundle

        group:
            class:          Sonata\UserBundle\Admin\Document\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle