vich_uploader:
    db_driver: mongodb
    mappings:
        default_file:
            upload_destination: '%kernel.root_dir%/../web'
            directory_namer: App\Services\UploadDirectoryNamer
            namer: App\Services\UploadFileNamer    
        # if you add new image class, don't forget to add the relevant service in services_admin.yml