<?php

namespace App\Repository;

use Datetime;
use Doctrine\ODM\MongoDB\Repository\DocumentRepository;

/**
 * CategoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends DocumentRepository
{
    public function findRootCategories()
    {
        $qb = $this->query('Category');
        $qb->field('isRootCategory')->equals(true)->sort('index', 'asc');

        return $qb->execute();
    }
    
    public function findOlderCategories(Datetime $datetime) {
        $qb = $this->query('Category');
        $qb->addOr($qb->expr()->field('createdAt')->equals(null));
        $qb->addOr($qb->expr()->field('createdAt')->lt($datetime));

        return $qb->execute();
    }
}
