<?php

namespace App\Repository;

use Doctrine\ODM\MongoDB\Repository\DocumentRepository;
use Exception;

/**
 * AboutRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationRepository extends DocumentRepository
{
    public function findConfiguration()
    {
        $qb = $this->query('Configuration')
                   ->field('dbName')->exists(true) // fix bug on project creation, where two conf are created
                   ->sort('createdAt', 'DESC');

        $config = $qb->getQuery()->getSingleResult();
        $fromFixtureCommand = in_array("doctrine:mongodb:fixtures:load", $_SERVER['argv'] ?? []);
        if (!$config && !$fromFixtureCommand) { throw new NoConfigurationFound(); }
        return $config;
    }
}

class NoConfigurationFound extends Exception {}
