import './js/element-form/init-map'
import './js/element-form/check-and-send'
import './js/element-form/contributor-login'
import './js/element-form/geocode-address'
import './js/element-form/initialisation'
import './js/element-form/interactions'
import './js/element-form/geocode-address'
import './js/element-form/taxonomy-picker/taxonomy-picker-container.js'
import './js/element-form/keep-data'

import './js/vendor/bootstrap-datepicker.min.js'
import './js/vendor/timepicki'
