monolog:
    channels: ['commands', 'projects']
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
        command:
            type: stream
            path: "%kernel.logs_dir%/commands.log"
            level: info
            channels: ['commands']
        projects:
            type: stream
            path: "%kernel.logs_dir%/projects.log"
            level: info
            channels: ['projects']
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        # deprecation:
        #     type: stream
        #     path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        # deprecation_filter:
        #     type: filter
        #     handler: deprecation
        #     max_level: info
        #     channels: ["php"]
